author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Win32-EventLog
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  POE: 0.38
  Win32: 0
  Win32::EventLog: 0
version: 1.08
